export type DriveNode =
  | {
      type: 'folder'
      id: string
      title: string
      viewUrl: string
      children: DriveNode[]
    }
  | {
      type: 'file'
      id: string
      title: string
      viewUrl: string
      fileExtension?: string
      fileSize?: number
      modifiedTime?: string
    }

export const POSTERS_FOLDER_URL =
  'https://drive.google.com/drive/folders/1cbZeKgICK-g23VhZHyFHleSG_QnUrnpP'

export const POSTERS_TREE_FETCHED_AT = '2026-04-30'

export const POSTERS_TREE: DriveNode = {
  type: 'folder',
  id: "1cbZeKgICK-g23VhZHyFHleSG_QnUrnpP",
  title: "2026 Spring SR PROJ Posters",
  viewUrl: "https://drive.google.com/drive/folders/1cbZeKgICK-g23VhZHyFHleSG_QnUrnpP",
  children: [
    {
      type: 'folder',
      id: "1TIg4eisorO3pG-6q1UcPFSa0GYIH7tB7",
      title: "BATCH 2",
      viewUrl: "https://drive.google.com/drive/folders/1TIg4eisorO3pG-6q1UcPFSa0GYIH7tB7",
      children: [
        {
          type: 'folder',
          id: "1lDUtlLhcuElkkW1qvHA04x3debWFw565",
          title: "DONE",
          viewUrl: "https://drive.google.com/drive/folders/1lDUtlLhcuElkkW1qvHA04x3debWFw565",
          children: [
            {
              type: 'file',
              id: "1kyifhY1ZsuShmenA96YQ595ceMnxuO_v",
              title: "SHANG Southern California Applied Mathematics Symposium 2026.pdf",
              viewUrl: "https://drive.google.com/file/d/1kyifhY1ZsuShmenA96YQ595ceMnxuO_v/view?usp=drivesdk",
              fileExtension: "pdf",
              fileSize: 440318,
              modifiedTime: "2026-04-22T23:45:11.000Z",
            }
          ],
        },
        {
          type: 'file',
          id: "15oTQVku8ICxBqe9R0kfliNTmx_OIGH60",
          title: "ALMARZOUQ_ABDULLAH_Soteria.pdf",
          viewUrl: "https://drive.google.com/file/d/15oTQVku8ICxBqe9R0kfliNTmx_OIGH60/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 3607726,
          modifiedTime: "2026-04-22T23:44:13.000Z",
        },
        {
          type: 'file',
          id: "1IRTJQ_l9r9XNtr7IH6-mzTu5txz9RGzN",
          title: "AUGUST Drift poster (2).pdf",
          viewUrl: "https://drive.google.com/file/d/1IRTJQ_l9r9XNtr7IH6-mzTu5txz9RGzN/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 484414,
          modifiedTime: "2026-04-22T23:48:36.000Z",
        },
        {
          type: 'file',
          id: "197Q9Jsrd4j0tctpatau9JHyCv1a-wUZK",
          title: "BOWERS spike2text.pdf",
          viewUrl: "https://drive.google.com/file/d/197Q9Jsrd4j0tctpatau9JHyCv1a-wUZK/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1009632,
          modifiedTime: "2026-04-22T23:45:00.000Z",
        },
        {
          type: 'file',
          id: "1Ol1N_cU6iSpHMam2ldEwpYJ6fzGnoaKj",
          title: "DILLON JAY Goblin King II Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1Ol1N_cU6iSpHMam2ldEwpYJ6fzGnoaKj/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1012833,
          modifiedTime: "2026-04-22T23:48:21.000Z",
        },
        {
          type: 'file',
          id: "16jISVs62h7FqlIXdspfd1jeSSLU4Q24s",
          title: "HOLDEN STACKS Final Poster UPDATED.pdf",
          viewUrl: "https://drive.google.com/file/d/16jISVs62h7FqlIXdspfd1jeSSLU4Q24s/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2807396,
          modifiedTime: "2026-04-22T23:46:35.000Z",
        },
        {
          type: 'file',
          id: "1CrQPSARKHk87eo4V1npqOOWlUhsyFJCP",
          title: "HOVANNES UPDATED.pdf",
          viewUrl: "https://drive.google.com/file/d/1CrQPSARKHk87eo4V1npqOOWlUhsyFJCP/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 264895,
          modifiedTime: "2026-04-22T23:43:50.000Z",
        },
        {
          type: 'file',
          id: "1xRXjSa7wKJa7-JJakzk3d_M58awEkq7w",
          title: "Hunter_Jillian_Fusion.pdf",
          viewUrl: "https://drive.google.com/file/d/1xRXjSa7wKJa7-JJakzk3d_M58awEkq7w/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1119923,
          modifiedTime: "2026-04-22T23:44:43.000Z",
        },
        {
          type: 'file',
          id: "19Y68beMO8Mg1F_kwV_KHHo2IVmdc8lvr",
          title: "PIRATEZ By CJ Hansen,Doug Spaeth.pdf",
          viewUrl: "https://drive.google.com/file/d/19Y68beMO8Mg1F_kwV_KHHo2IVmdc8lvr/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 5089298,
          modifiedTime: "2026-04-22T23:49:07.000Z",
        },
        {
          type: 'file',
          id: "1VeYJykr0luMaDMswahtwr0OdZqa1M5A_",
          title: "RAZO MARCUS Cmsi4072Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1VeYJykr0luMaDMswahtwr0OdZqa1M5A_/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2592330,
          modifiedTime: "2026-04-22T23:45:32.000Z",
        },
        {
          type: 'file',
          id: "1C6NCoPKyi_P3vdPgfcg53j1Sf7YcMHcn",
          title: "SONA UPDATED SeniorProjectPoster.pdf",
          viewUrl: "https://drive.google.com/file/d/1C6NCoPKyi_P3vdPgfcg53j1Sf7YcMHcn/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 4634875,
          modifiedTime: "2026-04-22T23:48:04.000Z",
        },
        {
          type: 'file',
          id: "15w-i1V3UAef0vTVu_-GHmpGlQodw25DB",
          title: "UPDATED SMIGLA_TESSA_CollegeBaseballSim.pdf",
          viewUrl: "https://drive.google.com/file/d/15w-i1V3UAef0vTVu_-GHmpGlQodw25DB/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 14626596,
          modifiedTime: "2026-04-23T01:18:41.000Z",
        },
        {
          type: 'file',
          id: "1URYssQXZ3_v6Jt5BW6_hSaaD0ibaPHbC",
          title: "WESLEY VideoScholar - Poster-2.pdf",
          viewUrl: "https://drive.google.com/file/d/1URYssQXZ3_v6Jt5BW6_hSaaD0ibaPHbC/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1617845,
          modifiedTime: "2026-04-22T23:47:53.000Z",
        }
      ],
    },
    {
      type: 'folder',
      id: "1uChwOyrAlfvbxOEBl1hdX-xEfhPxW2vm",
      title: "BATCH 3",
      viewUrl: "https://drive.google.com/drive/folders/1uChwOyrAlfvbxOEBl1hdX-xEfhPxW2vm",
      children: [
        {
          type: 'file',
          id: "1NUG7aW9vMZ8CmaJRuYGHAWA7VUBy8mHb",
          title: "AHTZIRI RefugioPoster.pdf",
          viewUrl: "https://drive.google.com/file/d/1NUG7aW9vMZ8CmaJRuYGHAWA7VUBy8mHb/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 6870815,
          modifiedTime: "2026-04-26T04:42:04.000Z",
        },
        {
          type: 'file',
          id: "1J4RyWV0zr-aSooTubkhRYAmdVqQjtEEX",
          title: "BOYCE_ALLEN_Coven.pdf",
          viewUrl: "https://drive.google.com/file/d/1J4RyWV0zr-aSooTubkhRYAmdVqQjtEEX/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 26763027,
          modifiedTime: "2026-04-24T22:39:41.000Z",
        },
        {
          type: 'file',
          id: "188_cSd5TG7M6Z4kf_S8cT6uEecC0njtp",
          title: "DE JESUS Memoria Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/188_cSd5TG7M6Z4kf_S8cT6uEecC0njtp/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 3901122,
          modifiedTime: "2026-04-24T22:35:50.000Z",
        },
        {
          type: 'file',
          id: "1PrRKhYfmpmPrmdE4kcVw0oGhj9iD1jGx",
          title: "DINH Presto.pdf",
          viewUrl: "https://drive.google.com/file/d/1PrRKhYfmpmPrmdE4kcVw0oGhj9iD1jGx/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 3312023,
          modifiedTime: "2026-04-24T22:37:52.000Z",
        },
        {
          type: 'file',
          id: "1VLoOzR-so7SfrpA0oosW3D51wHHptfhs",
          title: "FELTON Schedulr Poster Updated.pdf",
          viewUrl: "https://drive.google.com/file/d/1VLoOzR-so7SfrpA0oosW3D51wHHptfhs/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 7053387,
          modifiedTime: "2026-04-24T22:35:13.000Z",
        },
        {
          type: 'file',
          id: "1R9pno7s6X1XDlBW0k0gxZODJ_2JR_PSZ",
          title: "GARCIA Game Dev.pdf",
          viewUrl: "https://drive.google.com/file/d/1R9pno7s6X1XDlBW0k0gxZODJ_2JR_PSZ/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1609471,
          modifiedTime: "2026-04-30T01:16:10.489Z",
        },
        {
          type: 'file',
          id: "11rspDmy2o1kcp6A77CtTv2FoqHuF-hHw",
          title: "GUNAWAN final poster.pdf",
          viewUrl: "https://drive.google.com/file/d/11rspDmy2o1kcp6A77CtTv2FoqHuF-hHw/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2008473,
          modifiedTime: "2026-04-24T22:37:13.000Z",
        },
        {
          type: 'file',
          id: "120S3kHrtsd_BLq5hwjXsNV_T9XnrfU7c",
          title: "MATTON Briefcase Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/120S3kHrtsd_BLq5hwjXsNV_T9XnrfU7c/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1045379,
          modifiedTime: "2026-04-24T22:39:28.000Z",
        },
        {
          type: 'file',
          id: "10zfmuNnV4aC4_YG4EZlRvC-sB_mYtPob",
          title: "MAZZIER OvrUndrPosterProposal.pdf",
          viewUrl: "https://drive.google.com/file/d/10zfmuNnV4aC4_YG4EZlRvC-sB_mYtPob/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2545914,
          modifiedTime: "2026-04-26T00:17:05.000Z",
        },
        {
          type: 'file',
          id: "1hczD1pmx-17gMYum1cSoM6IVyJLPKuPQ",
          title: "PHELPS Senior Project - Finance Buddy S2 (1).pdf",
          viewUrl: "https://drive.google.com/file/d/1hczD1pmx-17gMYum1cSoM6IVyJLPKuPQ/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 5672647,
          modifiedTime: "2026-04-27T23:19:36.000Z",
        },
        {
          type: 'file',
          id: "1C4Iv2SBaspwQtYH9f20RXGf01JEg1s_g",
          title: "QUIOGUE Hangful_Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1C4Iv2SBaspwQtYH9f20RXGf01JEg1s_g/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 889812,
          modifiedTime: "2026-04-24T22:38:07.000Z",
        },
        {
          type: 'file',
          id: "17cYKSTJLyvE9IinBEmzOOa26SfosN7qo",
          title: "RHODES Demonstrating Optical Parallelism for Linear Algebra Operations.pdf",
          viewUrl: "https://drive.google.com/file/d/17cYKSTJLyvE9IinBEmzOOa26SfosN7qo/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2971910,
          modifiedTime: "2026-04-24T22:38:46.000Z",
        },
        {
          type: 'file',
          id: "1GOQ5gsinOkLXC701I-wQorZKOU0quOou",
          title: "SANTOS Posterv1.pdf",
          viewUrl: "https://drive.google.com/file/d/1GOQ5gsinOkLXC701I-wQorZKOU0quOou/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 231335,
          modifiedTime: "2026-04-24T22:38:19.000Z",
        },
        {
          type: 'file',
          id: "1cIUAaLR6k8c2Ya4Vv7lKi4LRX4GvBtgT",
          title: "Scolari_Cameron_ThesisCoTAutoPreferencePairs.pdf.pdf",
          viewUrl: "https://drive.google.com/file/d/1cIUAaLR6k8c2Ya4Vv7lKi4LRX4GvBtgT/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1418170,
          modifiedTime: "2026-04-24T22:34:50.000Z",
        },
        {
          type: 'file',
          id: "1HWFXW1HDlhUXMOG8iiA7F8DKUMggCQJA",
          title: "SEGURA BarScout Senior Project Poster Updatated.pdf",
          viewUrl: "https://drive.google.com/file/d/1HWFXW1HDlhUXMOG8iiA7F8DKUMggCQJA/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2059676,
          modifiedTime: "2026-04-24T22:36:21.000Z",
        },
        {
          type: 'file',
          id: "1zuh79xAb_oOmWm9Ja2Z6RzN5eL1aZjMf",
          title: "SOTO JaydenSoto_Anisuggest+_Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1zuh79xAb_oOmWm9Ja2Z6RzN5eL1aZjMf/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 3250465,
          modifiedTime: "2026-04-26T04:41:25.000Z",
        },
        {
          type: 'file',
          id: "1osEJAlhxouVEr9frv7GOocdNc_D6AtFc",
          title: "SPAETH final poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1osEJAlhxouVEr9frv7GOocdNc_D6AtFc/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 4070040,
          modifiedTime: "2026-04-24T22:36:12.000Z",
        },
        {
          type: 'file',
          id: "1PhHVQ6Hn8H69DbKN-cT6ILB0uvM4wZ2q",
          title: "TARAZI Final_Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1PhHVQ6Hn8H69DbKN-cT6ILB0uvM4wZ2q/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 819370,
          modifiedTime: "2026-04-24T22:39:10.000Z",
        },
        {
          type: 'file',
          id: "1Gz05ktZJZTYEAtyJwiiuNQaRSu8MdHbZ",
          title: "YOO PHISHGUARD POSTER.pdf",
          viewUrl: "https://drive.google.com/file/d/1Gz05ktZJZTYEAtyJwiiuNQaRSu8MdHbZ/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 329888,
          modifiedTime: "2026-04-24T22:35:33.000Z",
        }
      ],
    },
    {
      type: 'folder',
      id: "1unAfsSdnwm2dm_qaXgg75ZGvoKNKellA",
      title: "DONE",
      viewUrl: "https://drive.google.com/drive/folders/1unAfsSdnwm2dm_qaXgg75ZGvoKNKellA",
      children: [
        {
          type: 'file',
          id: "1pL2d2E_tZDfaOI8HsvExw7SmyAh7SFt5",
          title: "ADI Roitburg_Adi_SniperKitty.pdf",
          viewUrl: "https://drive.google.com/file/d/1pL2d2E_tZDfaOI8HsvExw7SmyAh7SFt5/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 17693315,
          modifiedTime: "2026-04-21T22:55:16.000Z",
        },
        {
          type: 'file',
          id: "1MhYrA0lQ6RkVjGbACwV1PlcZAf3X_Ys7",
          title: "ELIA Seniro project Poster (final) copy.pdf",
          viewUrl: "https://drive.google.com/file/d/1MhYrA0lQ6RkVjGbACwV1PlcZAf3X_Ys7/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 110345904,
          modifiedTime: "2026-04-21T22:58:59.000Z",
        },
        {
          type: 'file',
          id: "1UuA1guIL8bU77_rde_sTLC643Xp1uEsY",
          title: "ELIASI UPDATED Eliasi_Giselle_Echo.pdf",
          viewUrl: "https://drive.google.com/file/d/1UuA1guIL8bU77_rde_sTLC643Xp1uEsY/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 1500788,
          modifiedTime: "2026-04-21T23:31:32.000Z",
        },
        {
          type: 'file',
          id: "1X4cT8PA-CXOID8sQuSlT8Ybe02TG337-",
          title: "GALVIN Galvin_Kate_Archival.pdf",
          viewUrl: "https://drive.google.com/file/d/1X4cT8PA-CXOID8sQuSlT8Ybe02TG337-/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 5797015,
          modifiedTime: "2026-04-21T23:26:55.000Z",
        },
        {
          type: 'file',
          id: "1RymQPrkDd152iJrYLSaeq2EwhotJIC7g",
          title: "HANSEN By CJ Hansen,Doug Spaeth.pdf",
          viewUrl: "https://drive.google.com/file/d/1RymQPrkDd152iJrYLSaeq2EwhotJIC7g/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 5089298,
          modifiedTime: "2026-04-21T23:32:06.000Z",
        },
        {
          type: 'file',
          id: "1rioOlUW55V1qyDjGMjnIF8B_OrXnKLSL",
          title: "KUSHAL Jayaswal_Kushal_Bookshelf.pdf",
          viewUrl: "https://drive.google.com/file/d/1rioOlUW55V1qyDjGMjnIF8B_OrXnKLSL/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 9727803,
          modifiedTime: "2026-04-21T23:26:30.000Z",
        },
        {
          type: 'file',
          id: "17JdMTRXGsniOoXKDZSeUWCQo4MmgDyeX",
          title: "MILO Poker Face - Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/17JdMTRXGsniOoXKDZSeUWCQo4MmgDyeX/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 834264,
          modifiedTime: "2026-04-21T23:23:54.000Z",
        },
        {
          type: 'file',
          id: "1bLYsgAVCMJboxsyUACvEJT3yvI75SFAs",
          title: "NOLAN AscotMicroForestPoster.pdf",
          viewUrl: "https://drive.google.com/file/d/1bLYsgAVCMJboxsyUACvEJT3yvI75SFAs/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2753006,
          modifiedTime: "2026-04-21T23:24:20.000Z",
        },
        {
          type: 'file',
          id: "12BKk8YDHwEeaxFFfJwPbsG6miGvqfY3c",
          title: "REITICH_SAMUEL_CloudCrashers.pdf",
          viewUrl: "https://drive.google.com/file/d/12BKk8YDHwEeaxFFfJwPbsG6miGvqfY3c/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 4035115,
          modifiedTime: "2026-04-21T23:26:02.000Z",
        },
        {
          type: 'file',
          id: "1pL6iyePSgvEs1SrIg2sCFiB2r8oqIFqO",
          title: "RHODES CARSON Demonstrating Optical Parallelism for Linear Algebra Operations.pdf",
          viewUrl: "https://drive.google.com/file/d/1pL6iyePSgvEs1SrIg2sCFiB2r8oqIFqO/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 2971910,
          modifiedTime: "2026-04-21T22:54:24.000Z",
        },
        {
          type: 'file',
          id: "1evUShY951PvZFc700xEfErlkjxdP3cgg",
          title: "ROCHA UPark Poster.pdf",
          viewUrl: "https://drive.google.com/file/d/1evUShY951PvZFc700xEfErlkjxdP3cgg/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 3037463,
          modifiedTime: "2026-04-21T23:24:03.000Z",
        },
        {
          type: 'file',
          id: "1CNhg5KqzktrF8cC3UAqozwKpj6JjvnHF",
          title: "STEFAN LionRoar.pdf",
          viewUrl: "https://drive.google.com/file/d/1CNhg5KqzktrF8cC3UAqozwKpj6JjvnHF/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 5119112,
          modifiedTime: "2026-04-21T22:55:34.000Z",
        }
      ],
    },
    {
      type: 'folder',
      id: "1IaXlexGpR1ehAMlGRNWb-iFYUqhUygi7",
      title: "EDC SPRING 2026 Posters",
      viewUrl: "https://drive.google.com/drive/folders/1IaXlexGpR1ehAMlGRNWb-iFYUqhUygi7",
      children: [
        {
          type: 'file',
          id: "1nWZIB3coZYJzfThWrqDmZ_H5YddAvZAG",
          title: "JIMENEZ_ISABELA_TILTTABLE.pdf",
          viewUrl: "https://drive.google.com/file/d/1nWZIB3coZYJzfThWrqDmZ_H5YddAvZAG/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 607088,
          modifiedTime: "2026-04-27T23:21:06.000Z",
        },
        {
          type: 'file',
          id: "1OBmVjdRwhy-0jqeTjxyI6KNGUSE1aOMh",
          title: "OMAR Fracture Toughness Group Poster 2026 Design Showcase.pdf",
          viewUrl: "https://drive.google.com/file/d/1OBmVjdRwhy-0jqeTjxyI6KNGUSE1aOMh/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 426633,
          modifiedTime: "2026-04-28T08:45:59.000Z",
        },
        {
          type: 'file',
          id: "18uI05-FRMeeeJfOmvN5B0Ao_E4OW2shG",
          title: "REID_PETER_BanningPassWaterDistrictWaterTreatmentPlant.pdf",
          viewUrl: "https://drive.google.com/file/d/18uI05-FRMeeeJfOmvN5B0Ao_E4OW2shG/view?usp=drivesdk",
          fileExtension: "pdf",
          fileSize: 4860806,
          modifiedTime: "2026-04-27T23:20:57.000Z",
        }
      ],
    },
    {
      type: 'file',
      id: "173ebTm-5u9z_0PFCasqqKu99y5scXLnH",
      title: "GARCIA CMSI-4072 Poster.pdf",
      viewUrl: "https://drive.google.com/file/d/173ebTm-5u9z_0PFCasqqKu99y5scXLnH/view?usp=drivesdk",
      fileExtension: "pdf",
      fileSize: 3998219,
      modifiedTime: "2026-04-30T01:16:43.000Z",
    }
  ],
}
